{% set version = "0.15.1" %}

package:
  name: lychee
  version: {{ version }}

source:
  url: https://github.com/lycheeverse/lychee/archive/v{{ version }}.tar.gz
  sha256: 21c52aab5eefb0fda578f8192dffc5b776954e585f5692b87079cbb52ac1d89c

build:
  number: 1

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

test:
  requires:
    - m2-grep  # [win]
  commands:
    - lychee --version
    - lychee --help
    - lychee --version | grep -iE "{{ version.replace('.', '\.') }}"

about:
  home: https://lychee.cli.rs
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast, async, resource-friendly link checker
  dev_url: https://github.com/lycheeverse/lychee
  doc_url: https://lychee.cli.rs/introduction
  description: |
    Finds broken URLs and mail addresses inside Markdown, HTML,
    reStructuredText, websites and more!

extra:
  recipe-maintainers:
    - danielnachun
