{% set version = "0.21.0" %}

package:
  name: lychee
  version: {{ version }}

source:
  url: https://github.com/lycheeverse/lychee/archive/refs/tags/lychee-v{{ version }}.tar.gz
  sha256: 15a5f4d1a3c8f8819cc1772c4b703d081dbb4dd57dea9e6fa60e25de8add15d6

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

test:
  requires:
    - m2-grep  # [win]
  commands:
    - lychee --version
    - lychee --help
    - lychee --version | grep -iE {{ version.replace('.', '\.') }}

about:
  home: https://lychee.cli.rs
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast, async, resource-friendly link checker
  dev_url: https://github.com/lycheeverse/lychee
  doc_url: https://lychee.cli.rs/introduction
  description: |
    Finds broken URLs and mail addresses inside Markdown, HTML,
    reStructuredText, websites and more!

extra:
  recipe-maintainers:
    - danielnachun
    - egpbos
