schema_version: 1

context:
  version: "0.24.2"

package:
  name: lychee
  version: ${{ version }}

source:
  url: https://github.com/lycheeverse/lychee/archive/refs/tags/lychee-v${{ version }}.tar.gz
  sha256: 62687c0a84ceec76d17e30e494dcf8e65c7099a2e24a6a521a41854b8eb3759d

build:
  number: 1
  skip: ppc64le
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
      OPENSSL_DIR: ${{ '${PREFIX}' if unix else '%LIBRARY_PREFIX%' }}
      OPENSSL_NO_VENDOR: "1"
    content:
      - cargo auditable install --bins --locked --no-track --profile=release --path=lychee-bin --root="${{ '${PREFIX}' if unix else '%LIBRARY_PREFIX%' }}"
      - cargo-bundle-licenses --format=yaml --output=THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - package_contents:
      strict: true
      bin:
        - lychee
  - script:
      - lychee --help
      - lychee --version
      - lychee --version | ${{ 'grep -iE ' if unix else 'findsr /r /c:' }}${{ version | replace('.', '\\.') }}

about:
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast, async, resource-friendly link checker
  description: |
    Finds broken URLs and mail addresses inside Markdown, HTML,
    reStructuredText, websites and more!

  homepage: https://lychee.cli.rs
  repository: https://github.com/lycheeverse/lychee
  documentation: https://lychee.cli.rs/introduction

extra:
  recipe-maintainers:
    - danielnachun
    - egpbos
