schema_version: 1

context:
  version: "0.23.0"

package:
  name: lychee
  version: ${{ version }}

source:
  url: https://github.com/lycheeverse/lychee/archive/refs/tags/lychee-v${{ version }}.tar.gz
  sha256: 0c2c7387f5c8916c8c35ffd6102507663de8645da78579231a403020c34db67b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - requirements:
      run:
        - if: win
          then: m2-grep
    script:
      - lychee --version
      - lychee --help

about:
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fast, async, resource-friendly link checker
  description: |
    Finds broken URLs and mail addresses inside Markdown, HTML,
    reStructuredText, websites and more!


  homepage: https://lychee.cli.rs
  repository: https://github.com/lycheeverse/lychee
  documentation: https://lychee.cli.rs/introduction

extra:
  recipe-maintainers:
    - danielnachun
    - egpbos
